export const USER_SIGN_UP_RESULT = "USER_LOGIN_RESULT";

export const ADD_BASKET = "ADD_BASKET";
export const VACATE_BASKET = "VACATE_BASKET";
export const DELETE_BEER = "DELETE_BEER";
export const ADD_USERINFO = "ADD_USERINFO";
